//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecpMgmtWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessPermissionTbl
    {
        public int UserId { get; set; }
        public int AccessId { get; set; }
        public int PermissionId { get; set; }
    
        public virtual AccessTbl AccessTbl { get; set; }
        public virtual PermissionTbl PermissionTbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
